### ISSUE TITLE
Add Skulk Sensor Texture

### ISSUE THREAD

**Issue by Den4enko** [GeyserMC/GeyserOptionalPack#21]
Is it possible to add texture and sounds for this block?

**Comment by Camotoy** [comment]
Possible? Probably. Do we intend on doing this? Probably not, because it will be obsolete in six months if 1.18 comes out in December. You might be able to nab the Caves and Cliffs resource pack from a beta client instance and apply it to players to see the block texture.

**Comment by Den4enko** [comment]
Okay. I understood. Thank you for answer.

**Comment by NicoBooze** [comment]
do not know whether that will help, is currently also held for 1.17.

https://mcpedl.com/f3-pe-mod/
