### ISSUE TITLE
[Suggestion] Glass Panel as java

### ISSUE THREAD

**Issue by TheDiego845** [GeyserMC/GeyserOptionalPack#25]
My suggestion is that, add to the texture pack a texture that makes the same glass panel look the same as in java.

**Comment by Camotoy** [comment]
Thanks for the suggestion! There are already packs that do this, such as https://mcpedl.com/vanilla-deluxe-mixed-ui/. Therefore, because Geyser isn't needed for these changes, we don't think it's necessary to implement. Thanks anyway!

**Comment by TheDiego845** [comment]
> Thanks for the suggestion! There are already packs that do this, such as https://mcpedl.com/vanilla-deluxe-mixed-ui/. Therefore, because Geyser isn't needed for these changes, we don't think it's necessary to implement. Thanks anyway!

But that texture pack does not include the glass panels

**Comment by Camotoy** [comment]
Sorry! https://mcpedl.com/lukass-java-parity-pack/ this one was the one.

**Comment by TheDiego845** [comment]
The problem with this texture is that it works but it is very laggy and it is created for version 1.16

**Comment by lukeeey** [comment]
> Sorry! https://mcpedl.com/lukass-java-parity-pack/ this one was the one.

That pack claims to do this but it doesn't. In fact I can't find it anywhere and I can't figure out how to implement it.
