### ISSUE TITLE
Remove iron golem cracking (for 1.18.10)

### ISSUE THREAD

**Issue by Camotoy** [GeyserMC/GeyserOptionalPack#28]
Looks like beta 1.18.10.26 adds iron golem cracking, so we can remove our workaround for it then.

**Comment by FlowpxD** [comment]
U Can Delete The Textures I Think They Should Keep that Cuz still some player play below 1.18.10

**Comment by Konicai** [comment]
Geyser doesn't support 1.18.x anymore

**Comment by Kas-tle** [comment]
@Camotoy this was done a while ago if you want to close
