### ISSUE TITLE
add support hex color

### ISSUE THREAD

**Issue by TOWUK** [GeyserMC/GeyserOptionalPack#32]
i just join on be server and see it nex gradient in chat and nicknames, how to create support this feature?
![image](https://user-images.githubusercontent.com/28830162/177195365-0d0b7990-3435-490a-864b-7581ec1df475.png)

**Comment by Kas-tle** [comment]
I would need to see the pack to confirm but I am fairly sure this is just using emoji. See https://wiki.bedrock.dev/concepts/emojis.html.

**Comment by TOWUK** [comment]
> I would need to see the pack to confirm but I am fairly sure this is just using emoji. See https://wiki.bedrock.dev/concepts/emojis.html.

oh really. you were right...![image](https://user-images.githubusercontent.com/28830162/177353816-5b8a2b13-8a73-4291-8bc1-441acbdc9aac.png)

**Comment by TypicalShavonne** [comment]
> > I would need to see the pack to confirm but I am fairly sure this is just using emoji. See https://wiki.bedrock.dev/concepts/emojis.html.
> 
> well, here is the texture pack, look, no, it seems to me that there should still be support for the white text [soul.zip](https://github.com/GeyserMC/GeyserOptionalPack/files/9047243/soul.zip)

that server clearly stole some of HIVE resources 😂

**Comment by Camotoy** [comment]
Seeing as this is not true hex colors, I am closing.
